"""
Responsibility-theme extraction and classification across the JD corpus.

Parses the "responsibilities" section out of each data/<jd_id>/jd_archive.md
(handles clean markdown headings, unstructured plain-text scrapes, and
condensed single-paragraph summaries), then classifies each bullet against a
fixed 16-theme taxonomy via keyword matching (multi-label — a bullet can hit
more than one theme).

For JDs the regex extractor can't parse at all (prose-only descriptions,
non-English heading phrasing, thin scrapes), falls back to
responsibility_bullets_llm.json — a hand/agent-curated jd_id -> [bullets] map
built by reading those files directly and interpreting the responsibilities,
rather than pattern-matching. Each output record's "source" field marks which
path produced it ("regex" or "llm_interpreted"). That fallback file is not
regenerated by this script; rebuild it (e.g. via an agent) when new
unparseable JDs show up, using the same jd_id keys.

Inputs (read from analysis/):
  responsibility_bullets_llm.json    — optional LLM-interpreted fallback bullets

Also cross-tabs the 16 responsibility themes against the Layer B codebook dimensions
in data.json (seniority, autonomy_level, jd_authorship, data_team_maturity, etc.) to
surface which specific responsibilities go with which behavioural traits. Pairs where
a theme's regex keywords and a dimension's own coding rubric detect the same textual
signal (e.g. the "Data Quality & Testing" theme vs. `testing_framing`) are flagged as
construct-overlap and excluded from the reported findings — crossing them would mostly
measure whether two classification methods agree with each other, not a substantive
relationship. See OVERLAP_PAIRS below and "Responsibility themes vs. Layer B dimensions"
in the generated .md for the full reasoning, including two relationships that were
manually stratification-checked (confounder-controlled) before being reported, and one
that looked real unstratified and was kept specifically as a documented negative result.

Outputs (written to analysis/):
  responsibility_bullets.json        — raw extracted bullets per JD, tagged by source
  responsibility_classification.json — per-JD theme sets + corpus-wide stats + example quotes + dimension relationships
  responsibility_taxonomy.md         — human-readable taxonomy reference + examples + dimension relationships

Run:
  python3 analysis/responsibility_taxonomy.py
"""

import re
import json
import glob
import math
from pathlib import Path
from collections import defaultdict, Counter
from scipy.stats import chi2_contingency

ROOT = Path(__file__).parent.parent
DATA_DIR = ROOT / "data"
OUT_DIR = Path(__file__).parent

# ---------------------------------------------------------------------------
# Section extraction — pulls bullet/line content out of the responsibilities
# section of each jd_archive.md, tolerating both markdown headings and the
# heading-less plain-text scrapes that later postings used.
# ---------------------------------------------------------------------------

START_RE = re.compile(
    r'^(your |key |main |core |primary |essential )?responsibilit(y|ies)$'
    r'|^key job responsibilit(y|ies)$'
    r'|^task(s)?( and responsibilit(y|ies))?$'
    r'|^you will be responsible (to|for)$'
    r'|^what you.ll be up to'
    r'|^what you.[dl]l? (do|be doing|be working on|work on|own|tackle)( in.*)?$'
    r'|^what you will (do|be doing|work on|own|tackle)$'
    r'|^what you.ll achieve:?$'
    r'|^what will you do$'
    r'|^your (role|impact|day.to.day|mission)$'
    r'|^the role$'
    r'|^in this role:?$'
    r'|^main tasks( and responsibilities)?$'
    r'|^tasks and remit$'
    r'|^responsibilities and tasks:?$'
    r'|^role (summary|overview|description)$'
    r'|^day.to.day$'
    r'|^in this role.*you.ll$'
    # Bounded to 60 chars and requires a leading "As a/an" + a trailing "you will" -
    # checked against the corpus for false positives (see 2026-08-01 audit): every
    # line matching this shape was a genuine role-title clause opening the
    # responsibilities section, not an unrelated sentence with the same words.
    # Path 2 (the only path this pattern is used from) additionally restricts
    # START_RE to lines under 70 chars, bounding the risk further.
    r'|^as (a|an) .{2,60}, ?you will:?$'
    r'|^in this role,? you will\.{0,2}$'
    r'|^your (key )?(activities and )?responsibilit(y|ies):?$'
    r'|^your daily tasks$'
    r'|^the impact you.ll (have|make)$'
    r'|^how you.ll (spend your time|make an impact)$',
    re.I,
)

STOP_RE = re.compile(
    r'^about (you|us|the team|preply|bolt)'
    r'|^requirements'
    r'|^qualifications'
    r'|^must have'
    r'|^nice to have'
    r'|^good to have'
    r'|^bonus'
    r'|^preferred'
    r'|^why (you|join)'
    r'|^perks'
    r'|^benefits'
    r'|^what we offer'
    r'|^equal opportunit'
    r'|^diversity'
    r'|^apply now'
    r'|^who (you are|we are)'
    r'|^our (values|benefits)'
    r'|^compensation'
    r'|^salary'
    r'|^interview process'
    r'|^hiring process'
    r'|^tech stack'
    r'|^stack$'
    r'|^what you( will)? need'
    r'|^what you.ll need'
    r'|^what you bring'
    r'|^skills'
    r'|^experience'
    r'|^you (have|are|bring|hold|possess)'
    r'|^location'
    r'|^employment type'
    r'|^department'
    r'|^workplace'
    r'|^type$'
    r'|^profil recherch'
    r'|^do you have what it takes'
    r'|^play your part'
    r"|^what.s in it for you"
    r'|^applications are reviewed',
    re.I,
)


CONDENSED_RESP_RE = re.compile(
    r'\b(?:Key |Main |Core )?Responsibilit(?:y|ies):\s*(.+)'
)
CONDENSED_STOP_RE = re.compile(
    r'\b(Requirements?|Skills?|Tools?|Tech(?:nology)? [Ss]tack|Team|Role|Qualifications?|Experience)\s*:',
)


def extract_condensed_paragraph(text: str) -> list[str]:
    """Handles the single-paragraph scrape format used by some batches:
    'Role blurb. Responsibilities: item one; item two; item three. Requirements: ...'
    — everything is one paragraph, semicolon-delimited, no bullets/headings.
    """
    m = CONDENSED_RESP_RE.search(text)
    if not m:
        return []
    rest = m.group(1)
    stop = CONDENSED_STOP_RE.search(rest)
    if stop:
        rest = rest[: stop.start()]
    parts = [p.strip(" .") for p in rest.split(";")]
    return [p for p in parts if len(p) > 10]


def extract_responsibility_bullets(text: str) -> list[str]:
    """Best-effort extraction of responsibility bullets from one jd_archive.md body."""
    lines = text.split("\n")

    # Path 1: clean markdown headings (## or ###). A matched section's end
    # boundary is the next heading at the SAME OR SHALLOWER level — a nested
    # subheading (e.g. "### Data Culture" under "## Key Responsibilities")
    # must not truncate the section, or everything after the first
    # subsection silently disappears.
    headings = [
        (i, len(l) - len(l.lstrip("#")), l.lstrip("#").strip())
        for i, l in enumerate(lines)
        if l.startswith("## ") or l.startswith("### ")
    ]
    if headings:
        collected = []
        for idx, (i, level, h) in enumerate(headings):
            hh = h.strip().rstrip(":")
            if START_RE.match(hh):
                start = i + 1
                end = len(lines)
                for j in range(idx + 1, len(headings)):
                    if headings[j][1] <= level:
                        end = headings[j][0]
                        break
                for bl in lines[start:end]:
                    bl = bl.strip()
                    if bl.startswith("- "):
                        collected.append(bl[2:].strip())
                    elif bl and not bl.startswith("#") and len(bl) > 15:
                        collected.append(bl)
        if collected:
            return collected

    # Path 2: heading-less plain-text scrape — each non-empty line is a unit;
    # a short, unpunctuated line matching START_RE opens the section, a short
    # line matching STOP_RE (or looking like a new section header) closes it.
    flat = [l.strip() for l in text.split("\n") if l.strip()]
    collected = []
    in_section = False
    count = 0
    for p in flat:
        # rstrip(".:?") not just ":" - some JD authors close a heading with a
        # stylistic ellipsis ("In this role, You will.."), double period, or
        # question mark ("What will you do?"), which the old ":"-only strip
        # left trailing, tripping the `not pp.endswith(".")` guard below and
        # silently making a genuine short heading register as a prose
        # sentence instead. Confirmed via the L'Oréal ("In this role, You
        # will..") and Aubay Portugal ("What will you do?") JDs in the
        # 2026-08-01 audit.
        pp = p.rstrip(".:?")
        short = len(pp) < 70 and not pp.endswith(".")
        if short and START_RE.match(pp):
            in_section = True
            count = 0
            continue
        if in_section:
            if short and STOP_RE.match(pp):
                in_section = False
                continue
            if short and count > 0 and re.match(r"^[A-Z][a-zA-Z ,&/'\-]{2,60}$", pp) and not p.endswith("."):
                in_section = False
                continue
            if len(p) > 15:
                collected.append(p)
            count += 1
            if count > 25:
                in_section = False
    if collected:
        return collected

    # Path 3 (fallback): condensed single-paragraph scrapes —
    # "Role blurb. Responsibilities: item one; item two. Requirements: ..."
    # — used by some batches where the whole posting is one summarized
    # paragraph with no headings or line breaks to key off of.
    return extract_condensed_paragraph(text)


def clean_bullet(b: str) -> str:
    b = re.sub(r"^[\-\*••]+\s*", "", b)
    b = re.sub(r"\*\*", "", b)
    return b.strip()


# ---------------------------------------------------------------------------
# Taxonomy — 15 responsibility themes, keyword-matched (multi-label per bullet).
# Each pattern was tuned against a manual read of a random bullet sample, then
# checked against the corpus-wide leftover ("uncategorized") pool.
#
# GAP FOUND AND FIXED 2026-08-01 (corpus n=395): an uncategorized-bullet audit
# found "AI & Agentic Workflows" was missing despite being a real, sizeable
# pattern — 130/349 parsed JDs (37%) had at least one responsibility bullet
# referencing AI/ML/agentic work, 40 of 178 such bullets matched no theme at
# all, and the rest scattered into loosely-related themes (Data Modeling, BI
# & Reporting, Pipeline Engineering) purely on incidental keyword overlap.
# Layer B already had a whole-JD codebook dimension for this (`ai_role`:
# none/ai_user/ai_enabler, coded on 132/395 = 33% of the corpus) — the gap
# was specifically that the finer-grained, per-bullet taxonomy had no
# counterpart theme. Added as the 16th theme below; see AI_FALSE_POSITIVE_RE
# for the one false-positive collision found and excluded (Looker/LookML "ML
# models" ≠ machine learning), and OVERLAP_PAIRS for why this theme is
# construct-overlapping with `ai_role` and excluded from relationship
# findings the same way "Data Quality & Testing" is excluded against
# `testing_framing`. Deliberately scoped to AI/ML/agentic content only, not
# general "automate/automation" language — see the theme's own inline
# comment for why bare "automat*" was left out.
#
# Two smaller, lower-priority patterns noticed in the same audit, deliberately
# NOT proposed as new themes (too small / too structurally different to be
# worth a 17th theme):
#   - Client/customer-facing responsibilities (client relationship management,
#     presales, business development) appear in ~10 JDs, concentrated in
#     consultancies/agencies (Turner & Townsend, Mantel Group, Holistics,
#     Joon Solutions, etc.). Real pattern, but narrow enough — and different
#     enough from the internal-single-employer framing every other theme
#     assumes — that folding it in would need its own employment-model
#     handling, not just a regex.
#   - Non-English bullets are invisible to every theme (regex vocabulary is
#     English-only) — e.g. 2 Dutch bullets in klimaatroute's JD ("Bewaken en
#     verbeteren van de prestaties...") land in "uncategorized" purely
#     because of language, not content. Confirmed as a parser/vocabulary
#     limitation (1 JD, 2 bullets) rather than a corpus-wide issue worth a
#     multi-language taxonomy investment at current scale.
# ---------------------------------------------------------------------------

TAXONOMY = {
    # "data model(s)" bare (no "modeling"/"build ... models" wrapper) was entirely missed -
    # e.g. "Design data models facilitating analysis", "Contributing to the ongoing design
    # of our core data model" - despite being the most direct possible phrasing for this
    # theme. Added as its own alternative rather than loosening to bare "model(s)", which
    # would risk catching statistical/ML model or "business model" bullets unrelated to
    # data modeling. "data product(s)" is the modern synonym for a trusted, reusable
    # dataset - this theme's own description - and was likewise uncategorized.
    "Data Modeling & Transformation": r'\b(data model(l)?(ing|s)?\b|dbt model|semantic (layer|model)|data mart|star schema|dimensional model|DAX|LookML|transform(ation)?s?\b|build.*models|reusable (data )?models|metrics? (layer|definition)|business logic|data product)',
    # Bare "integrat(e/ion)" was deliberately left out (catches "GitHub Copilot integration",
    # "continuous integration"/CI, unrelated) - but "data source(s)" + "integrat*" close
    # together, in either order, is unambiguous pipeline-ingestion language ("integrate new
    # data sources", "data source integrations via APIs") and was falling through entirely
    # since only the exact phrase "data integration" was covered. Window is bounded to a
    # few words rather than unbounded .* so an unrelated "integration" and an unrelated,
    # distant "data sources" mention in the same long bullet can't falsely pair up.
    "Pipeline Engineering & Orchestration": r'\b(pipeline|ETL|ELT|ingest(ion)?|orchestrat|airflow|dagster|prefect|data flows?|data integration|data sources?\b(?:\W+\w+){0,6}?\W+integrat|integrat\w*(?:\W+\w+){0,6}?\W+data sources?\b)',
    "Data Quality & Testing": r'\b(data quality|test(ing|s)?\b|validat|monitor(ing)?|assertion|anomaly|reliability|accura(cy|te)|observability|data trust|Monte Carlo)',
    "Governance & Documentation": r'\b(governance|catalog|metadata|access control|documentation|document\b|lineage|compliance|standards?\b|single (source|version) of truth|certified metrics)',
    "Stakeholder Collaboration & Requirements": r'\b(stakeholder|collaborat|partner with|cross-functional|business (needs|requirements|users)|translate|liais|bridg(e|ing)|link between|align(ment)?|requirements gathering|work(ing)? closely with|works? with (customer|end.user)s?)',
    "BI & Reporting/Dashboards": r'\b(dashboard|report(ing|s)?\b|visuali[sz]ation|Looker\b|Tableau\b|Power ?BI|Grafana|BI (tool|layer|developer)|self-service (analytics|reporting)?)',
    # scal(e|ability|able) and bare strategy/strategic were dropped: they matched "scalable
    # analytics"/"as the platform scales" and any unrelated "strategic X" with no architecture
    # content. Scoped variants below require a data/platform/tech object alongside them.
    # "data platform" (the noun - "our data platform", "the Data Platform team") is the most
    # common phrasing for this theme's subject matter and was missing entirely; only
    # "platform (design|strategy)" was covered before.
    # "data delivery platform" is a specific product name in this corpus (PGGM's internal
    # platform) but reads as generic "data platform" phrasing, so covered here too.
    "Architecture & Platform Strategy": r'\b(architecture|data (delivery )?platform|platform (design|strategy)|scalab(le|ility) (data|pipeline|platform|architecture|system)s?|infrastructure|tech(nical|nology)? stack( strateg(y|ies))?|system design|roadmap|(data|platform|technical|technology) strateg(y|ies)|strategic (data|platform|direction|decision))',
    # "self-serve" is the more common phrasing in this corpus but was missing entirely
    # (only "self-service" was matched), silently undercounting this theme.
    "Self-Service Enablement & Data Literacy": r'\b(self-serv(e|ice)|data literacy|training|enable(ment)?|educat|champion.*(practice|literacy)|drop-in sessions|knowledge.shar)',
    # Bare "lead(ing|ership)" conflated people/team leadership with technical or project
    # leadership ("lead the architecture", "lead cross-domain projects") - two different
    # constructs this theme's own description says it separates. "lead" now only counts
    # when paired with team/people language; mentor/coach/hire/etc. stay bare since those
    # are already people-specific. Bare "leadership" was dropped too - in this corpus it's
    # overwhelmingly used as a stakeholder-audience noun ("reporting to leadership",
    # "collaborating with... leadership teams"), not the JD-holder's own leadership; only
    # "provide/technical leadership" phrasing describes the role's own leadership.
    "Mentorship & Leadership": r'\b(mentor|lead(ing|ership)?\b\s*(,|and)?\s*(mentor|develop|grow|coach)?\s*(a |the )?team\b|\bteam lead\b|lead(ing)? a team of|\bas a lead\b|\bas the lead\b|carry expertise as a lead|(provide|providing) (technical )?leadership|technical leadership|manage (a|the) team|coach|hire|hiring|grow (the )?team|line manag|people manag|guide (junior|other))',
    "Performance & Cost Optimization": r'\b(performance|cost (optimi[sz]ation|efficiency|reduction)|efficien(cy|t)|optimi[sz]e)',
    "Data Infrastructure & Warehouse Ops": r'\b(warehouse|data lake|infrastructure|CI/CD|version control|cloud\b|devops|Snowflake|BigQuery|Redshift|Databricks|Terraform)',
    "Business Analysis & Insight Generation": r'\b(insight|analy[sz]e|analytics? (to support|for)|decision.making|forecast|experiment(ation)?|A/B test|KPI|metrics? (tracking|definition)|business (impact|problems|decisions))',
    # Bare "tooling" was the single biggest precision problem in the whole taxonomy: 23/32
    # of this theme's matches were bare "tooling", and the large majority of those are just
    # "using/improving/BI tooling" - ordinary tool usage, not the evaluation/selection this
    # theme's own description promises ("Evaluating/selecting third-party tools and
    # vendors"). Narrowed to require actual evaluation/selection/adoption language attached.
    "Vendor & Tooling Evaluation": r'\b(vendor|tool(ing)? selection|evaluat\w* (new )?tool|evaluat\w*.{0,20}vendor|new tooling|tooling adoption|third.party)',
    # Bare "risk\b" mostly matched "Risk" as a stakeholder team/department name
    # ("trading, risk, and finance stakeholders", "Risk Controlling", "Risk/Compliance
    # team") rather than data privacy/security risk, which is this theme's actual intent.
    # Narrowed to risk-management/assessment/scoring language and data/privacy/compliance
    # risk specifically.
    "Security, Privacy & Risk": r'\b(privacy|security\b|risk (management|mitigation|assessment|scoring|model)|data risk|privacy risk|compliance risk|PII|GDPR|complian)',
    # Bare "own(ership)" matched "taking ownership of personal development", "accelerate
    # your own output" - reflexive/career language, not data ownership. Excluded explicitly
    # rather than narrowing "own" itself, since the vast majority of "own"/"ownership" hits
    # in this corpus are genuinely about data/product ownership and a data-object
    # allowlist would have been longer and more brittle than this short denylist.
    "Data Ownership (end-to-end)": r'\b(own(ership)?\b|end.to.end|full.stack|from ingestion to)',
    # Added 2026-08-01 after an uncategorized-bullet audit found 130/349 parsed JDs
    # (37%) had at least one AI/agentic-referencing bullet, 40 of which matched no
    # theme at all and the rest scattered into unrelated themes purely on incidental
    # keyword overlap (e.g. "AI-generated code" landing in Data Quality & Testing
    # only because it also said "review"). This is the bullet-level counterpart to
    # the existing whole-JD `ai_role` Layer B dimension (none/ai_user/ai_enabler,
    # coded on 132/395 = 33% of the corpus) — see OVERLAP_PAIRS below, this theme
    # is construct-overlapping with `ai_role` by design and excluded from findings
    # the same way "Data Quality & Testing" is excluded against `testing_framing`.
    # Deliberately scoped to AI/ML/agentic content only, not general automation —
    # a smaller "automate internal work" cluster found in the same audit (~10
    # bullets) was about half AI-tool-driven ("automate reconciliation tasks" via
    # Claude Code/Cursor, already caught here) and half unrelated process
    # automation with no AI framing at all; folding bare "automat*" in here would
    # have pulled in that unrelated half and diluted what this theme measures.
    "AI & Agentic Workflows": r'\b(AI|ML|machine learning|LLM|GenAI|generative AI|agentic|AI agents?|AI-assisted|AI-driven|AI-powered|AI-native|AI coding|copilot|prompts?)\b',
}

# Applied after an "own(ership)" match to drop reflexive/career-development false positives
# (see comment on Data Ownership above). Matched independently of TAXONOMY so it only
# suppresses this one theme's false positives without touching any other pattern.
OWNERSHIP_FALSE_POSITIVE_RE = re.compile(
    r'\b(your|my)\s+own\s+(\w+\s+)?(output|words|pace|time|career|personal development|professional development|development)\b'
    r'|\bownership of (personal|your own)\b'
    r'|\btaking ownership of personal\b',
    re.I,
)

# Applied after a "transform(ation)" match to drop the two recurring non-data-modeling
# false-positive shapes: "digital transformation" (an org-change buzzword) and
# "transform X into Y" where X is an abstract noun (ambiguity/complexity/challenges),
# a soft-skill metaphor rather than data transformation.
TRANSFORM_FALSE_POSITIVE_RE = re.compile(
    r'\bdigital transformation\b'
    r'|\btransform (it|them|challenges|ambiguity|complexity) into\b',
    re.I,
)

# Applied after an AI & Agentic Workflows match to drop the one recurring false
# positive found in the 2026-08-01 audit: "ML" as a bare abbreviation for a
# Looker/LookML model artifact ("BI tool semantic layer (ML models, explores,
# derived tables)"), not machine learning. Scoped narrowly to that Looker/BI-tool
# context specifically, rather than suppressing "ML models" everywhere, since a
# bullet like "train and deploy ML models for churn prediction" with no other AI
# keyword is a genuine machine-learning reference and must still match.
AI_FALSE_POSITIVE_RE = re.compile(
    r'\bLooker\b.{0,40}\bML models?\b'
    r'|\bsemantic layer\s*\(\s*ML models?\b',
    re.I,
)

TAXONOMY_DESCRIPTIONS = {
    "Data Modeling & Transformation": "Building/maintaining dbt models, semantic layers, metrics definitions, dimensional models — turning raw data into trusted, reusable structures.",
    "Pipeline Engineering & Orchestration": "ETL/ELT pipelines, ingestion, orchestration tooling (Airflow/Dagster/Prefect), moving data end to end.",
    "Data Quality & Testing": "Tests, validation, monitoring, anomaly detection, data trust/observability.",
    "Governance & Documentation": "Cataloging, metadata, access control, lineage, documentation, standards, compliance frameworks.",
    "Stakeholder Collaboration & Requirements": "Partnering with business/analyst/engineering stakeholders, translating requirements, cross-functional alignment.",
    "BI & Reporting/Dashboards": "Dashboards, reporting, visualization tools (Looker, Tableau, Power BI, Grafana), self-service BI.",
    "Architecture & Platform Strategy": "System/data architecture, platform design, scalability, tech-stack decisions, roadmap/strategy.",
    "Self-Service Enablement & Data Literacy": "Enabling others to self-serve, training, data literacy programs, knowledge-sharing.",
    "Mentorship & Leadership": "Mentoring, leading a team, hiring, coaching, people management.",
    "Performance & Cost Optimization": "Improving query/pipeline performance, cost efficiency, resource optimization.",
    "Data Infrastructure & Warehouse Ops": "Warehouse platform work (Snowflake/BigQuery/Redshift/Databricks), CI/CD, cloud infra, Terraform.",
    "Business Analysis & Insight Generation": "Generating insight, supporting decisions, forecasting, experimentation/A-B testing, KPI definition.",
    "Vendor & Tooling Evaluation": "Evaluating/selecting third-party tools and vendors.",
    "Security, Privacy & Risk": "Data privacy, security, PII/GDPR handling, risk management.",
    "Data Ownership (end-to-end)": "Explicit end-to-end/full-stack ownership language, independent of which stage.",
    "AI & Agentic Workflows": "Using AI/agentic tools to accelerate the candidate's own work (Claude Code, Cursor, Copilot), or building data infrastructure that AI/ML systems consume or run on — the bullet-level counterpart to the `ai_role` Layer B dimension.",
}

COMPILED = {k: re.compile(v, re.I) for k, v in TAXONOMY.items()}

# Manually-curated fallback for JDs the regex extractor can't parse (prose-only,
# non-English headings, or thin scrapes) — a jd_id -> [bullets] map produced by
# reading each file and interpreting it directly. See responsibility_bullets_llm.json.
# Regenerate this file by hand/agent when new unparseable JDs show up; it is not
# rebuilt automatically by this script.
LLM_FALLBACK_PATH = OUT_DIR / "responsibility_bullets_llm.json"


def compute_dedup_delta(jd_theme_sets, jd_list):
    """The corpus re-scrapes some postings across dates (same company+role,
    different jd_id). Collapsing to one record per distinct posting and
    recomputing theme % shows how much that duplication skews the headline
    numbers — returns the largest absolute percentage-point shift across
    all themes.
    """
    sig_to_ids = defaultdict(list)
    for j in jd_list:
        m = re.match(r"\d{4}-\d{2}-\d{2}_(.+)", j["jd_id"])
        sig = m.group(1) if m else j["jd_id"]
        sig_to_ids[sig].append(j["jd_id"])

    dedup_ids = set()
    for ids in sig_to_ids.values():
        ids_sorted = sorted(ids)
        with_bullets = [i for i in ids_sorted if jd_theme_sets.get(i)]
        dedup_ids.add(with_bullets[0] if with_bullets else ids_sorted[0])

    n_full = sum(1 for v in jd_theme_sets.values() if v)
    n_dedup = sum(1 for i in dedup_ids if jd_theme_sets.get(i))
    if n_full == 0 or n_dedup == 0:
        return 0.0

    full_counts = Counter(t for themes in jd_theme_sets.values() for t in themes)
    dedup_counts = Counter(t for i in dedup_ids for t in jd_theme_sets.get(i, []))

    max_delta = 0.0
    for t in full_counts:
        full_pct = 100 * full_counts[t] / n_full
        dedup_pct = 100 * dedup_counts[t] / n_dedup
        max_delta = max(max_delta, abs(dedup_pct - full_pct))
    return round(max_delta, 1)


# ---------------------------------------------------------------------------
# Responsibility themes x Layer B dimensions.
#
# Pairs flagged here share a textual trigger between the theme's regex keywords
# (TAXONOMY above) and the dimension's own LLM coding rubric (.claude/skills/
# classify-jd/SKILL.md) or a tech-stack flag whose tool name is literally one of
# the theme's keywords. Crossing an overlapping pair mostly measures whether two
# classification methods agree with each other, not a substantive relationship —
# they're excluded from "clean findings" rather than reported as weak ones.
# ---------------------------------------------------------------------------
OVERLAP_PAIRS = {
    ("Data Quality & Testing", "testing_framing"),
    ("Security, Privacy & Risk", "domain_risk"),
    ("Security, Privacy & Risk", "loss_aversion_framing"),
    ("Data Ownership (end-to-end)", "autonomy_level"),
    ("Data Modeling & Transformation", "has_dbt"),
    ("BI & Reporting/Dashboards", "has_looker"),
    ("BI & Reporting/Dashboards", "has_tableau"),
    ("BI & Reporting/Dashboards", "has_power_bi"),
    ("Data Infrastructure & Warehouse Ops", "has_snowflake"),
    ("Data Infrastructure & Warehouse Ops", "has_databricks"),
    ("Pipeline Engineering & Orchestration", "has_airflow"),
    ("AI & Agentic Workflows", "ai_role"),
}

DIMENSIONS_TO_TEST = [
    "seniority", "domain_risk", "velocity_vs_rigour", "autonomy_level",
    "data_team_maturity", "stakeholder_orientation", "role_type", "jd_authorship",
    "ai_role", "testing_framing", "loss_aversion_framing", "work_arrangement",
    "greenfield_vs_fix", "has_dbt", "has_python", "has_airflow", "has_looker",
    "has_tableau", "has_power_bi",
]


def cramers_v(chi2, n, r, c):
    return math.sqrt(chi2 / (n * (min(r - 1, c - 1))))


def theme_dimension_chi2(jd_theme_sets, jd_meta, theme, dim):
    """2xk contingency table: theme present (yes/no) x dimension value.
    Valid even though theme membership is multi-label per JD — each (theme, dim)
    test only looks at one binary theme-indicator at a time, independent of
    whichever other themes also matched the same JD."""
    counts = defaultdict(lambda: [0, 0])  # dim_value -> [n_with_theme, n_total]
    for jd_id, themes in jd_theme_sets.items():
        meta = jd_meta.get(jd_id)
        if not meta:
            continue
        val = meta.get(dim)
        if val is None or val == "":
            continue
        has_theme = theme in themes
        counts[val][1] += 1
        if has_theme:
            counts[val][0] += 1
    if len(counts) < 2:
        return None
    table = [[v[0], v[1] - v[0]] for v in counts.values()]
    n = sum(v[1] for v in counts.values())
    if n < 20:
        return None
    chi2, p, dof, expected = chi2_contingency(table)
    v = cramers_v(chi2, n, len(table), 2)
    return {"n": n, "chi2": round(chi2, 2), "p": p, "V": round(v, 3), "min_exp": round(expected.min(), 2)}


def crosstab_pct(jd_theme_sets, jd_meta, theme, dim, dim_values=None):
    """% of JDs matching `theme`, grouped by `dim` value."""
    counts = defaultdict(lambda: [0, 0])
    for jd_id, themes in jd_theme_sets.items():
        meta = jd_meta.get(jd_id)
        if not meta:
            continue
        val = meta.get(dim)
        if val is None or val == "":
            continue
        counts[val][1] += 1
        if theme in themes:
            counts[val][0] += 1
    values = dim_values or sorted(counts.keys())
    return {v: (round(100 * counts[v][0] / counts[v][1]) if counts[v][1] else None, counts[v][1]) for v in values if v in counts}


def compute_dimension_relationships(jd_theme_sets, jd_meta):
    themes = sorted({t for v in jd_theme_sets.values() for t in v})
    all_results = []
    for theme in themes:
        for dim in DIMENSIONS_TO_TEST:
            stats = theme_dimension_chi2(jd_theme_sets, jd_meta, theme, dim)
            if not stats:
                continue
            overlap = (theme, dim) in OVERLAP_PAIRS
            all_results.append({"theme": theme, "dimension": dim, "overlap": overlap, **stats})

    all_results.sort(key=lambda r: -r["V"])
    overlap_results = [r for r in all_results if r["overlap"]]
    clean_results = [
        r for r in all_results
        if not r["overlap"] and r["p"] < 0.01 and r["min_exp"] >= 5
    ]

    # Featured relationships: hand-picked from the clean list and stratification-
    # checked against a plausible confounder before being reported as findings
    # (see the .md write-up for the checks themselves). Hardcoded rather than
    # auto-selected because "does this survive a confound check" isn't something
    # this script can decide on its own — it's a judgment call re-made by a human
    # (or an agent) each time the featured set changes, not derived mechanically.
    featured = [
        {
            "theme": "Mentorship & Leadership", "dimension": "autonomy_level",
            "stratify_by": "seniority", "stratify_values": ["mid", "senior"],
            "survives": True,
        },
        {
            "theme": "Data Infrastructure & Warehouse Ops", "dimension": "jd_authorship",
            "stratify_by": None, "survives": None,  # not independently stratification-checked
        },
        {
            "theme": "Self-Service Enablement & Data Literacy", "dimension": "data_team_maturity",
            "stratify_by": None, "survives": None,
        },
    ]
    for f in featured:
        f["overall"] = theme_dimension_chi2(jd_theme_sets, jd_meta, f["theme"], f["dimension"])
        f["crosstab"] = crosstab_pct(jd_theme_sets, jd_meta, f["theme"], f["dimension"])
        if f["stratify_by"]:
            f["strata"] = {}
            for stratum_val in f["stratify_values"]:
                stratified_meta = {
                    jd_id: m for jd_id, m in jd_meta.items()
                    if m.get(f["stratify_by"]) == stratum_val
                }
                f["strata"][stratum_val] = crosstab_pct(jd_theme_sets, stratified_meta, f["theme"], f["dimension"])

    # Documented negative example: looked real unstratified, didn't survive a
    # maturity control. Kept as a worked demonstration of why every pairing
    # above needed the same kind of check, not just the featured three.
    debunked_theme, debunked_dim = "Architecture & Platform Strategy", "work_arrangement"
    debunked = {
        "theme": debunked_theme, "dimension": debunked_dim,
        "overall": theme_dimension_chi2(jd_theme_sets, jd_meta, debunked_theme, debunked_dim),
        "crosstab": crosstab_pct(jd_theme_sets, jd_meta, debunked_theme, debunked_dim,
                                   dim_values=["hybrid", "remote", "onsite", "not_stated"]),
        "strata": {},
    }
    for stratum_val in ["early", "mid", "mature"]:
        stratified_meta = {
            jd_id: m for jd_id, m in jd_meta.items()
            if m.get("data_team_maturity") == stratum_val
        }
        debunked["strata"][stratum_val] = crosstab_pct(
            jd_theme_sets, stratified_meta, debunked_theme, debunked_dim,
            dim_values=["hybrid", "remote", "onsite", "not_stated"],
        )

    return {
        "n_pairs_tested": len(all_results),
        "overlap_pairs_tested": overlap_results,
        "clean_findings": clean_results,
        "featured": featured,
        "debunked_example": debunked,
    }


def main():
    jd_dirs = sorted(DATA_DIR.glob("*/jd_archive.md"))
    jd_list = json.load(open(ROOT / "analysis" / "data.json"))
    jd_meta = {d["jd_id"]: d for d in jd_list}
    llm_fallback = {}
    if LLM_FALLBACK_PATH.exists():
        llm_fallback = json.loads(LLM_FALLBACK_PATH.read_text(encoding="utf-8"))

    bullets_by_jd = []
    n_llm_used = 0
    for f in jd_dirs:
        jd_id = f.parent.name
        text = f.read_text(encoding="utf-8")
        bullets = extract_responsibility_bullets(text)
        source = "regex"
        if not bullets and jd_id in llm_fallback and llm_fallback[jd_id]:
            bullets = llm_fallback[jd_id]
            source = "llm_interpreted"
            n_llm_used += 1
        bullets_by_jd.append({"jd_id": jd_id, "bullets": bullets, "source": source})

    n_with_bullets = sum(1 for r in bullets_by_jd if r["bullets"])
    print(f"  (of which {n_llm_used} filled from LLM-interpreted fallback)")
    (OUT_DIR / "responsibility_bullets.json").write_text(
        json.dumps(bullets_by_jd, indent=1), encoding="utf-8"
    )

    # --- classify ---
    jd_theme_sets = {}
    theme_bullet_counts = Counter()
    examples = defaultdict(list)
    # Full per-bullet hits, every bullet (not capped), tagged with the jd_id and the
    # matched keyword span(s) so the HTML can show "why" a bullet was tagged and
    # link back to the posting it came from.
    bullets_by_theme = defaultdict(list)
    uncategorized = []
    n_bullets_considered = 0
    n_bullets_with_theme = 0

    for rec in bullets_by_jd:
        jd_id = rec["jd_id"]
        if not rec["bullets"]:
            continue
        themes_for_jd = set()
        for raw in rec["bullets"]:
            b = clean_bullet(raw)
            if len(b) < 10:
                continue
            n_bullets_considered += 1
            matches = {cat: pat.search(b) for cat, pat in COMPILED.items()}
            # Re-search each theme's pattern past every false-positive span in turn, so a
            # bullet that legitimately matches elsewhere (e.g. "dbt models" later in a bullet
            # that opens with "digital transformation") isn't dropped just because *a* false
            # positive occurs somewhere in the text - only a match whose own span overlaps
            # a false-positive span gets skipped.
            for cat, fp_re in (
                ("Data Ownership (end-to-end)", OWNERSHIP_FALSE_POSITIVE_RE),
                ("Data Modeling & Transformation", TRANSFORM_FALSE_POSITIVE_RE),
                ("AI & Agentic Workflows", AI_FALSE_POSITIVE_RE),
            ):
                m = matches.get(cat)
                while m and any(
                    fp.start() < m.end() and fp.end() > m.start()
                    for fp in fp_re.finditer(b)
                ):
                    m = COMPILED[cat].search(b, m.end())
                matches[cat] = m
            matched = {cat for cat, m in matches.items() if m}
            if not matched:
                uncategorized.append(b)
            else:
                n_bullets_with_theme += 1
            for m in sorted(matched):
                theme_bullet_counts[m] += 1
                if len(examples[m]) < 12:
                    examples[m].append(b)
                bullets_by_theme[m].append({
                    "jd_id": jd_id,
                    "bullet": b,
                    "matched_text": matches[m].group(0),
                })
            themes_for_jd |= matched
        jd_theme_sets[jd_id] = sorted(themes_for_jd)

    theme_jd_counts = Counter()
    for themes in jd_theme_sets.values():
        for t in themes:
            theme_jd_counts[t] += 1

    theme_rows = []
    for cat, cnt in theme_jd_counts.most_common():
        theme_rows.append(
            {
                "theme": cat,
                "n_jds": cnt,
                "pct_of_jds": round(100 * cnt / n_with_bullets, 1),
                "n_bullets": theme_bullet_counts[cat],
            }
        )

    max_dedup_delta = compute_dedup_delta(jd_theme_sets, jd_list)

    # cross-tabs against role_type / seniority
    by_role = defaultdict(lambda: defaultdict(int))
    role_counts = Counter()
    by_seniority = defaultdict(lambda: defaultdict(int))
    seniority_counts = Counter()
    for jd_id, themes in jd_theme_sets.items():
        meta = jd_meta.get(jd_id)
        if not meta:
            continue
        rt = meta.get("role_type")
        sen = meta.get("seniority")
        role_counts[rt] += 1
        seniority_counts[sen] += 1
        for t in themes:
            by_role[rt][t] += 1
            by_seniority[sen][t] += 1

    # Scoped to the analytical cohort (AE/BI + team_lead), same as every other Layer B
    # finding in report.md — data_engineering/other role_types are a different discourse
    # population there (§3) and would silently skew these relationships otherwise.
    analytical_cohort_meta = {
        jd_id: m for jd_id, m in jd_meta.items()
        if m.get("role_type") in ("analytics_engineering_bi", "team_lead")
    }
    dimension_relationships = compute_dimension_relationships(jd_theme_sets, analytical_cohort_meta)

    classification = {
        "corpus_size": len(jd_list),
        "n_jds_with_parsed_responsibilities": n_with_bullets,
        "total_bullets_extracted": sum(len(r["bullets"]) for r in bullets_by_jd),
        "n_bullets_considered": n_bullets_considered,  # extracted bullets >=10 chars after cleaning
        "n_bullets_with_theme": n_bullets_with_theme,  # distinct bullets matching >=1 theme
        "total_theme_tags_assigned": sum(theme_bullet_counts.values()),  # sum over themes; >n_bullets_with_theme since bullets can multi-match
        "uncategorized_bullet_count": len(uncategorized),
        "max_dedup_delta_pct_points": max_dedup_delta,  # largest theme-% shift if re-scraped postings are collapsed to one per distinct posting
        "theme_stats": theme_rows,
        "jd_theme_sets": jd_theme_sets,
        "examples_by_theme": dict(examples),
        "bullets_by_theme": {k: v for k, v in bullets_by_theme.items()},
        "role_counts": dict(role_counts),
        "by_role": {k: dict(v) for k, v in by_role.items()},
        "seniority_counts": dict(seniority_counts),
        "by_seniority": {k: dict(v) for k, v in by_seniority.items()},
        "dimension_relationships": dimension_relationships,
    }
    (OUT_DIR / "responsibility_classification.json").write_text(
        json.dumps(classification, indent=1), encoding="utf-8"
    )

    write_taxonomy_md(
        theme_rows, examples, n_with_bullets, len(bullets_by_jd), n_llm_used,
        n_bullets_considered, n_bullets_with_theme, len(uncategorized), max_dedup_delta,
        dimension_relationships,
    )

    print(f"JDs with parsed responsibilities: {n_with_bullets} / {len(jd_list)}")
    print(f"Bullets extracted: {classification['total_bullets_extracted']}")
    for row in theme_rows:
        print(f"  {row['theme']:45s} {row['pct_of_jds']:5.1f}%  ({row['n_bullets']} bullets)")


def fmt_p(p):
    if p < 0.0001:
        return "p<0.0001"
    if p < 0.001:
        return "p<0.001"
    return f"p={p:.3f}" if p < 0.01 else f"p={p:.2f}"


def fmt_crosstab(crosstab):
    """crosstab: {value: (pct_or_None, n)} -> one line per value."""
    parts = []
    for val, (pct, n) in crosstab.items():
        parts.append(f"{val}: {pct}% (n={n})" if pct is not None else f"{val}: n/a (n={n})")
    return "; ".join(parts)


def write_relationships_section(lines, rel):
    lines.append("## Responsibility themes vs. Layer B dimensions\n")
    lines.append(
        "Each of the 15 responsibility themes is a binary per-JD indicator (matched at least one "
        "bullet, or didn't), so it can be crossed against any single-valued Layer B dimension as a "
        "standard 2×k contingency table (χ², Cramér's V) — this is valid even though a JD can match "
        "several themes at once, because each such test only looks at one theme's indicator in "
        "isolation, independent of which other themes also matched the same JD. Scoped to the "
        "analytical cohort (AE/BI + team_lead), same as every other Layer B finding in report.md — "
        "`data_engineering`/`other` role types are excluded here too.\n"
    )
    lines.append(
        "**The auto-correlation risk, and how it's handled:** several theme/dimension pairs are "
        "excluded from the findings below not because they're weak, but because they're circular — "
        "the theme's regex keywords and the dimension's own LLM coding rubric (or, for tech-stack "
        "flags, a literal tool name embedded in the theme's regex) detect the same textual signal. "
        "The single strongest pairing found in the entire sweep — \"Data Quality & Testing\" vs. "
        "`testing_framing`, Cramér's V=" + f"{next((r['V'] for r in rel['overlap_pairs_tested'] if r['theme']=='Data Quality & Testing' and r['dimension']=='testing_framing'), 0):.2f}" +
        " — is excluded on exactly this basis: `testing_framing` is coded by looking for testing/quality "
        "language in the JD, so crossing it against a theme built from testing/quality keywords mostly "
        "measures whether two classification methods agree with each other, not a substantive "
        "relationship. See `OVERLAP_PAIRS` in `responsibility_taxonomy.py` for the full list and the "
        "reasoning per pair.\n"
    )
    lines.append("### Construct-overlap pairs (validity checks, not findings)\n")
    lines.append("| Theme | Dimension | V | p | n |")
    lines.append("|---|---|---|---|---|")
    for r in rel["overlap_pairs_tested"]:
        lines.append(f"| {r['theme']} | {r['dimension']} | {r['V']:.2f} | {fmt_p(r['p'])} | {r['n']} |")
    lines.append("")

    lines.append(
        "### Clean relationships (p<0.01, min expected cell ≥5, no keyword overlap)\n"
    )
    lines.append(
        f"Ranked by effect size. These are exploratory — no multiple-comparison correction is applied "
        f"across the {rel['n_pairs_tested']} pairs tested in the full sweep, so p<0.01 alone should not "
        f"be read as strong evidence at this scale; effect size (V) and, ideally, a stratification check "
        f"(see below) matter more here than the p-value.\n"
    )
    lines.append("| Theme | Dimension | V | p | n |")
    lines.append("|---|---|---|---|---|")
    for r in rel["clean_findings"][:20]:
        lines.append(f"| {r['theme']} | {r['dimension']} | {r['V']:.2f} | {fmt_p(r['p'])} | {r['n']} |")
    lines.append("")

    lines.append("### Featured relationships, stratification-checked\n")
    lines.append(
        "Hand-picked from the clean list above and, for the first one, re-tested within subgroups of a "
        "plausible confounder before being written up as a finding — a check the rest of the clean list "
        "has *not* individually received, so treat anything not covered by name below as directional "
        "only, same as the rest of this document.\n"
    )
    for f in rel["featured"]:
        o = f["overall"]
        lines.append(f"**{f['theme']} × {f['dimension']}** — χ²={o['chi2']}, {fmt_p(o['p'])}, V={o['V']}, n={o['n']}\n")
        lines.append(f"- Overall: {fmt_crosstab(f['crosstab'])}")
        if f.get("stratify_by"):
            for stratum_val, ct in f["strata"].items():
                lines.append(f"- Within {f['stratify_by']}={stratum_val}: {fmt_crosstab(ct)}")
            verdict = "survives the stratification check — the gradient holds within each stratum, not just across the whole corpus" if f["survives"] else "did not survive the stratification check"
            lines.append(f"- **Verdict:** {verdict}.\n")
        else:
            lines.append("- Not independently stratification-checked beyond the overlap-keyword screen — read as directional.\n")

    d = rel["debunked_example"]
    lines.append("### A relationship that looked real and didn't survive scrutiny\n")
    o = d["overall"]
    lines.append(
        f"**{d['theme']} × {d['dimension']}** — unstratified: χ²={o['chi2']}, {fmt_p(o['p'])}, V={o['V']}, n={o['n']}. "
        f"Overall: {fmt_crosstab(d['crosstab'])}\n"
    )
    lines.append(
        "This pairing clears the same p<0.01 / no-overlap screen as the clean findings above, and on "
        "its own looks like a headline (\"remote roles get less architectural scope\"). It doesn't survive "
        "a stratification check against `data_team_maturity` — a plausible confounder, since maturity is "
        "independently correlated with work arrangement (mature teams skew hybrid) and with this theme:\n"
    )
    for stratum_val, ct in d["strata"].items():
        lines.append(f"- Within data_team_maturity={stratum_val}: {fmt_crosstab(ct)}")
    lines.append(
        "\nOnce split by maturity tier, `remote` stops being consistently the lowest group — `not_stated` "
        "is the consistently-lowest group in every tier instead, and several strata have single-digit "
        "cell counts for `remote`/`onsite`, which makes the unstratified comparison mostly noise rather "
        "than signal. Kept here as a documented negative result and a worked example of why a "
        "stratification check matters, not silently dropped.\n"
    )

    lines.append("### Critical assessment: how this whole approach could be wrong\n")
    lines.append(
        "- **Multiple comparisons.** The full sweep tests every theme against every dimension "
        f"({rel['n_pairs_tested']} pairs tested in total across all 16 themes) with no Bonferroni or FDR "
        "correction. At "
        "p<0.01 with that many tests, a meaningful number of the \"clean\" pairs are expected to be false "
        "positives by chance alone — the effect-size floor (V) and the stratification checks are the "
        "mitigation, not a substitute for treating this section as exploratory.\n"
        "- **Post-hoc selection.** The three featured relationships were picked *after* seeing which "
        "pairs had large effect sizes, then checked — not pre-registered. That ordering (see p-values, "
        "then decide what to scrutinize) is exactly the \"garden of forking paths\" pattern that makes "
        "exploratory findings less trustworthy than confirmatory ones. Only one of the three received an "
        "actual stratification check; the other two are reported with that caveat explicit, not implied.\n"
        "- **Two independent classification methods, two independent error rates.** Every relationship "
        "here compounds the regex classifier's error rate (§ uncategorized-bullet rate above) with "
        "whatever error rate the Layer B LLM coding carries on the paired dimension (`jd_authorship` "
        "self-consistency is 0.58 per report.md §3 — the lowest of any dimension) — a relationship "
        "involving `jd_authorship` specifically should be read with that codebook-ambiguity caveat "
        "layered on top of everything else in this section.\n"
        "- **Cross-sectional text, not causal evidence.** Every relationship here is a same-JD "
        "co-occurrence pattern in language written at one point in time. \"Mentorship language "
        "correlates with strategic autonomy language\" says nothing about whether one causes the other, "
        "or whether both are downstream of a third factor (company culture, team size) not coded in this "
        "corpus at all.\n"
        "- **The stratification checks themselves are not exhaustive.** Confirming a relationship "
        "survives a *single* plausible confounder (seniority, maturity) doesn't rule out a different "
        "confounder not tested — company size, sector, and funding stage are not coded dimensions in "
        "this corpus and could not be checked.\n"
        "- **Rebuttal most likely to land:** an outside reviewer's strongest objection would probably be "
        "the multiple-comparisons point combined with the fact that only one of the three featured "
        "relationships got an actual confounder check — the other two (`Data Infrastructure & Warehouse "
        "Ops × jd_authorship`, `Self-Service Enablement × data_team_maturity`) are reported at the same "
        "confidence level as a relationship that hasn't been stress-tested the way the debunked example "
        "shows this corpus can produce false leads. Treat those two as \"survived the overlap screen and "
        "a p<0.01/effect-size floor,\" not as \"confirmed.\"\n"
    )


def write_taxonomy_md(
    theme_rows, examples, n_with_bullets, corpus_size, n_llm_used,
    n_bullets_considered, n_bullets_with_theme, n_uncategorized, max_dedup_delta,
    dimension_relationships,
):
    n_regex = n_with_bullets - n_llm_used
    n_unrecovered = corpus_size - n_with_bullets
    pct_uncategorized = round(100 * n_uncategorized / n_bullets_considered, 1)
    lines = []
    lines.append("# Responsibility taxonomy\n")
    lines.append(
        f"Extracted from {n_with_bullets} of {corpus_size} JDs with an archived JD text file "
        f"(one JD in the corpus has a classification record but no archived raw text, so it's "
        f"excluded from this denominator entirely): "
        f"{n_regex} parsed directly (markdown headings, plain-text sections, or condensed "
        f"paragraph summaries), {n_llm_used} recovered via LLM interpretation of prose that "
        f"had no cleanly-parseable structure (see responsibility_bullets_llm.json). "
        f"{n_unrecovered} JDs have no extractable responsibilities at all — the source scrape "
        f"is a thin listing stub with zero role-content (verified by direct read, not assumed). "
        f"Regenerate with `python3 analysis/responsibility_taxonomy.py`.\n"
    )
    lines.append(
        f"Classification is rule-based keyword matching (see `responsibility_taxonomy.py::TAXONOMY`), "
        f"not per-line LLM judgment — treat this as a directional map, not a precise census. "
        f"Of {n_bullets_considered} extracted bullets, {n_bullets_with_theme} ({100-pct_uncategorized:.1f}%) "
        f"matched at least one theme; {n_uncategorized} ({pct_uncategorized}%) matched none (miscellaneous "
        f"duties too specific/rare to warrant their own theme — not a sign of missing bullets). "
        f"A bullet can match more than one theme, so theme percentages sum to well over 100%. "
        f"Each bullet's extraction source (`regex` vs `llm_interpreted`) is recorded per-JD in "
        f"responsibility_bullets.json.\n"
    )
    lines.append(
        f"The corpus was deduplicated at the source (data/ directories, keyed on normalized job-posting "
        f"URL — same company+role text alone was not treated as sufficient evidence, since several "
        f"pairs turned out to be genuinely distinct openings at different locations). A residual "
        f"same-company+role-text signature check against the current corpus (a cruder heuristic than "
        f"the URL-based dedup actually applied) still shows a spread of at most {max_dedup_delta} "
        f"percentage points per theme, confirming no further collapsing would change the ranking.\n"
    )
    lines.append("## Themes, ranked by share of JDs\n")
    lines.append("| Theme | % of JDs | # JDs | # bullets |")
    lines.append("|---|---|---|---|")
    for row in theme_rows:
        lines.append(f"| {row['theme']} | {row['pct_of_jds']}% | {row['n_jds']} | {row['n_bullets']} |")
    lines.append("")

    lines.append("## What each theme looks like\n")
    for row in theme_rows:
        cat = row["theme"]
        lines.append(f"### {cat} — {row['pct_of_jds']}% of JDs\n")
        lines.append(f"{TAXONOMY_DESCRIPTIONS[cat]}\n")
        lines.append(f"Keyword pattern: `{TAXONOMY[cat]}`\n")
        lines.append("Example bullets, verbatim from postings:\n")
        for ex in examples[cat][:10]:
            lines.append(f"- {ex}")
        lines.append("")

    write_relationships_section(lines, dimension_relationships)

    (OUT_DIR / "responsibility_taxonomy.md").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
